### ISSUE TITLE
Criar tabelas no banco de dados

### ISSUE THREAD

**Issue by dmontessi** [suasenha/suasenha#1]
- **curso: (id, nome)**
  
  Tabela será povoada com todos os cursos atendidos pelo sistema.
- **turno: (id, nome)**
  
  Tabela será povoada com todos os turnos disponíveis para atendimento.
- **secretaria: (id, nome, email, senha)**
  
  Tabela para cadastro das secretárias que irão realizar os atendimentos.
- **assunto: (id, nome, codigo)**
  
  Tabela contendo os tipos de atendimento, ou seja, as senhas que são distribuídas.
- **aluno: (id, nome, ra, semestre, celular, idcurso, idturno)**
  
  Tabela para cadastro dos alunos que solicitam atendimentos.
- **atendimento: (id, idaluno, idsecretaria, idassunto, dehdesejada, dehinicio, dehfim, problema, atendimento, finalizado)**
  
  Tabela de atendimento que funcionará como fila de atendimento.

**Comment by dmontessi** [comment]
# tabelas criadas

## curso

| coluna | tipo | auto increment | chave primária | nulo |
| --- | --- | --- | --- | --- |
| id | int(11) | ☑️ | ☑️ |  |
| nome | varchar(600) |  |  |  |

## turno

| coluna | tipo | auto increment | chave primária | nulo |
| --- | --- | --- | --- | --- |
| id | int(11) | ☑️ | ☑️ |  |
| nome | varchar(600) |  |  |  |

## secretaria

| coluna | tipo | auto increment | chave primária | nulo |
| --- | --- | --- | --- | --- |
| id | int(11) | ☑️ | ☑️ |  |
| nome | varchar(600) |  |  |  |
| email | varchar(600) |  |  |  |
| senha | varchar(600) |  |  |  |

## assunto

| coluna | tipo | auto increment | chave primária | nulo |
| --- | --- | --- | --- | --- |
| id | int(11) | ☑️ | ☑️ |  |
| nome | varchar(600) |  |  |  |
| código | varchar(600) |  |  |  |

## aluno

| coluna | tipo | auto increment | chave primária | nulo |
| --- | --- | --- | --- | --- |
| id | int(11) | ☑️ | ☑️ |  |
| nome | varchar(600) |  |  |  |
| ra | int(20) |  |  |  |
| semestre | int(2) |  |  |  |
| celular | int(10) |  |  |  |
| idcurso | int(11) |  |  |  |
| idturno | int(11) |  |  |  |

## atendimento

| coluna | tipo | auto increment | chave primária | nulo |
| --- | --- | --- | --- | --- |
| id | int(11) | ☑️ | ☑️ |  |
| idaluno | int(11) |  |  |  |
| idsecretaria | int(11) |  |  |  |
| idassunto | int(11) |  |  |  |
| dehdesejada | datetime |  |  |  |
| dehinicio | datetime |  |  | ☑️ |
| dehfim | datetime |  |  | ☑️ |
| problema | varchar(1000) |  |  | ☑️ |
| atendimento | varchar(1000) |  |  | ☑️ |
| finalizado | int(1) |  |  |  |

**Comment by dmontessi** [comment]
Verificado e constatado que todas as tabelas estão de acordo.

**Comment by dalbertjm** [comment]
O campo de nome do aluno está como auto increment e chave primária mesmo? Acho que esse campo não deve receber nenhuma das duas atribuições. De acordo?

**Comment by dmontessi** [comment]
Correto!

Foi apenas um erro de digitação, no banco de dados está correto.

![image](https://cloud.githubusercontent.com/assets/22962293/19600436/70d362cc-977b-11e6-8e14-9f4e5c90d54f.png)

Atualizado no comentário.
