### ISSUE TITLE
Aplicar restrições nas telas de acordo com o usuário

### ISSUE THREAD

**Issue by Weslleyvc** [suasenha/suasenha#10]
Aplicar restrições nas telas de acordo com o usuário.

**Comment by Weslleyvc** [comment]
Feito.

Aplicado as restrições nas telas.

**Comment by dmontessi** [comment]
Item de acordo.
- Ao acessar o sistema temos a tela de cadastro de atendimento, sem necessidade de login;
- Todas as outras telas são protegidas por login e senha.
