### ISSUE TITLE
Criar uma página "sobre"

### ISSUE THREAD

**Issue by Weslleyvc** [suasenha/suasenha#12]
Criar e alimentar uma página sobre, com as nossas informações e descrição do projeto.

**Comment by dmontessi** [comment]
Criada a página Sobre, disponível para acesso através da barra de menus do sistema e no endereço http://suasenha.com/Sobre

Precisamos pensar em um texto legal.

Alguma ideia do que podemos escrever? @flanogueira

**Comment by Weslleynds** [comment]
@dmontessi como anda este item?

**Comment by dmontessi** [comment]
indo

2017-06-28 11:16 GMT-04:00 Weslley Vilela <notifications@github.com>:
