### ISSUE TITLE
Definir os menus que serão exibidos

### ISSUE THREAD

**Issue by Weslleyvc** [suasenha/suasenha#14]
Definir os menus que serão exibidos aos usuários.

**Comment by dmontessi** [comment]
Atualmente, o sistema possui os menus INICIO, ATENDIMENTO, SECRETÁRIA e SOBRE.

Foi realizada uma validação no arquivo menu.php disponível no diretório /template/
- Quando o usuário (secretária) estiver logado o sistema irá apresentar todos os menus.
- Quando a sessão não estiver ativa, o sistema irá apresentar apenas os menus INÍCIO e SOBRE.
