### ISSUE TITLE
Ajustar os métodos de post

### ISSUE THREAD

**Issue by Weslleyvc** [suasenha/suasenha#8]
Ajustar os métodos de post para que não ocorra problemas com caracteres especiais.

**Comment by Weslleyvc** [comment]
Ajustado.

O problema estava na função "filter_input", deixada apenas nos campos de data do atendimento.

**Comment by dmontessi** [comment]
Item de acordo.
- Foi possível cadastrar o curso "Engenharia da Computação" que possui caracteres especiais.

Obrigado @Weslleyvc!
