### ISSUE TITLE
Criar tela de login para as secretárias

### ISSUE THREAD

**Issue by Weslleyvc** [suasenha/suasenha#9]
Criar tela de login para as secretárias.

**Comment by Weslleyvc** [comment]
Ajustada a tela de login (http://suasenha.com/login) e inserida a opção de login no menu superior.

**Comment by dmontessi** [comment]
Item de acordo.
- Na tela de login, foi possível logar utilizando o login da secretária cadastrada.
- Ao utilizar o login com uma senha incorreta, o sistema informa e não permite o login.

Obrigado @Weslleyvc!
